# Generated by Django 4.0.4 on 2022-05-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactus_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='password',
            new_name='tellme',
        ),
    ]
